const products = [
    {
      id: 1,
      name: "Hydrating Facial Cleanser",
      skinType: "Dry Skin",
      category: "Sữa rửa mặt",
      price: 25.99,
      image: "https://via.placeholder.com/200x150",
      description: "A gentle cleanser that hydrates dry skin while removing impurities.",
      ingredients: ["Hyaluronic Acid", "Glycerin", "Aloe Vera"],
      usage: "Apply to wet face, massage gently, and rinse.",
      rating: 4.5,
    },
    {
      id: 2,
      name: "Oil-Free Moisturizer",
      skinType: "Oily Skin",
      category: "Serum",
      price: 30.99,
      image: "https://via.placeholder.com/200x150",
      description: "A lightweight, oil-free moisturizer that controls shine.",
      ingredients: ["Salicylic Acid", "Green Tea Extract"],
      usage: "Apply a small amount to face and neck after cleansing.",
      rating: 4.2,
    },
    {
      id: 3,
      name: "Sensitive Skin Toner",
      skinType: "Normal Skin",
      category: "Toner",
      price: 22.99,
      image: "https://via.placeholder.com/200x150",
      description: "A gentle toner that soothes and balances sensitive skin.",
      ingredients: ["Chamomile", "Witch Hazel", "Rose Water"],
      usage: "Apply to a cotton pad and gently wipe over face after cleansing.",
      rating: 4.0,
    },
    {
      id: 4,
      name: "Vitamin C Serum",
      skinType: "All",
      category: "Serum",
      price: 45.99,
      image: "https://via.placeholder.com/200x150",
      description: "Brightens and protects skin with potent antioxidants.",
      ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid"],
      usage: "Apply a few drops to face and neck in the morning.",
      rating: 4.7,
    },
    {
      id: 5,
      name: "Gentle Makeup Remover",
      skinType: "Sensitive Skin",
      category: "Tẩy trang",
      price: 19.99,
      image: "https://via.placeholder.com/200x150",
      description: "Gently removes makeup without irritating sensitive skin.",
      ingredients: ["Micellar Water", "Aloe Vera", "Glycerin"],
      usage: "Saturate a cotton pad and gently wipe over face to remove makeup.",
      rating: 4.3,
    },
    {
      id: 6,
      name: "Acne Treatment Cream",
      skinType: "Oily Skin",
      category: "Kem trị mụn",
      price: 28.50,
      image: "https://via.placeholder.com/200x150",
      description: "Targets and treats acne breakouts effectively.",
      ingredients: ["Benzoyl Peroxide", "Tea Tree Oil"],
      usage: "Apply a thin layer to affected areas after cleansing.",
      rating: 3.9,
    },
    {
      id: 7,
      name: "Sun Protection SPF 50",
      skinType: "All",
      category: "Kem chống nắng",
      price: 32.00,
      image: "https://via.placeholder.com/200x150",
      description: "Provides broad-spectrum protection from harmful UV rays.",
      ingredients: ["Zinc Oxide", "Titanium Dioxide"],
      usage: "Apply liberally 15 minutes before sun exposure.",
      rating: 4.6,
    },
    {
      id: 8,
      name: "Night Repair Serum",
      skinType: "Dry Skin",
      category: "Serum",
      price: 55.00,
      image: "https://via.placeholder.com/200x150",
      description: "Repairs and rejuvenates skin overnight.",
      ingredients: ["Retinol", "Peptides", "Hyaluronic Acid"],
      usage: "Apply a few drops to face and neck at night.",
      rating: 4.8,
    },
    {
      id: 9,
      name: "Balancing Facial Wash",
      skinType: "Combination Skin",
      category: "Sữa rửa mặt",
      price: 24.75,
      image: "https://via.placeholder.com/200x150",
      description: "Cleanses and balances combination skin without stripping moisture.",
      ingredients: ["Salicylic Acid", "Charcoal", "Aloe Vera"],
      usage: "Apply to wet face, massage gently, and rinse.",
      rating: 4.1,
    },
    {
      id: 10,
      name: "Hydrating Toner Mist",
      skinType: "Dry Skin",
      category: "Toner",
      price: 27.99,
      image: "https://via.placeholder.com/200x150",
      description: "Instantly hydrates and refreshes dry skin.",
      ingredients: ["Hyaluronic Acid", "Rose Water", "Glycerin"],
      usage: "Mist onto face throughout the day as needed.",
      rating: 4.4,
    },
    {
      id: 11,
      name: "Micellar Cleansing Water",
      skinType: "All",
      category: "Tẩy trang",
      price: 18.50,
      image: "https://via.placeholder.com/200x150",
      description: "Gently removes makeup and impurities with micellar technology.",
      ingredients: ["Micellar Water", "Aloe Vera", "Chamomile"],
      usage: "Saturate a cotton pad and gently wipe over face to remove makeup.",
      rating: 4.2,
    },
    {
      id: 12,
      name: "Spot Treatment Gel",
      skinType: "Oily Skin",
      category: "Kem trị mụn",
      price: 29.99,
      image: "https://via.placeholder.com/200x150",
      description: "Quickly reduces the size and redness of acne spots.",
      ingredients: ["Benzoyl Peroxide", "Tea Tree Oil"],
      usage: "Apply a small amount directly to acne spots.",
      rating: 3.8,
    },
    {
      id: 13,
      name: "Daily Sunscreen Lotion",
      skinType: "Normal Skin",
      category: "Kem chống nắng",
      price: 34.50,
      image: "https://via.placeholder.com/200x150",
      description: "A lightweight sunscreen lotion for daily protection.",
      ingredients: ["Zinc Oxide", "Titanium Dioxide"],
      usage: "Apply liberally 15 minutes before sun exposure.",
      rating: 4.5,
    },
    {
      id: 14,
      name: "Advanced Anti-Aging Serum",
      skinType: "Combination Skin",
      category: "Serum",
      price: 62.00,
      image: "https://via.placeholder.com/200x150",
      description: "Reduces wrinkles and improves skin elasticity.",
      ingredients: ["Retinol", "Peptides", "Hyaluronic Acid"],
      usage: "Apply a few drops to face and neck at night.",
      rating: 4.9,
    },
    {
      id: 15,
      name: "Soothing Cleansing Balm",
      skinType: "Dry Skin",
      category: "Tẩy trang",
      price: 21.00,
      image: "https://via.placeholder.com/200x150",
      description: "Melt away makeup and impurities with this cleansing balm.",
      ingredients: ["Shea Butter", "Coconut Oil", "Vitamin E"],
      usage: "Massage onto dry face, then rinse with warm water.",
      rating: 4.3,
    },
    {
      id: 16,
      name: "Medicated Acne Wash",
      skinType: "Oily Skin",
      category: "Sữa rửa mặt",
      price: 26.50,
      image: "https://via.placeholder.com/200x150",
      description: "Clears acne and prevents future breakouts.",
      ingredients: ["Salicylic Acid", "Benzoyl Peroxide"],
      usage: "Apply to wet face, massage gently, and rinse.",
      rating: 4.0,
    },
    {
      id: 17,
      name: "Exfoliating Toner Pads",
      skinType: "Combination Skin",
      category: "Toner",
      price: 31.00,
      image: "https://via.placeholder.com/200x150",
      description: "Exfoliates and brightens skin with gentle acid.",
      ingredients: ["Glycolic Acid", "Lactic Acid", "Aloe Vera"],
      usage: "Wipe a pad over face after cleansing.",
      rating: 4.4,
    },
    {
      id: 18,
      name: "Broad Spectrum Sunscreen",
      skinType: "All",
      category: "Kem chống nắng",
      price: 38.00,
      image: "https://via.placeholder.com/200x150",
      description: "Provides broad-spectrum protection from harmful UV rays.",
      ingredients: ["Zinc Oxide", "Titanium Dioxide"],
      usage: "Apply liberally 15 minutes before sun exposure.",
      rating: 4.7,
    },
  ];

  export default products;