const products = [
  {
    id: 1,
    name: "Hydrating Facial Cleanser",
    skinType: "Dry Skin",
    category: "Sữa rửa mặt",
    price: 220000,
    image: "https://via.placeholder.com/200x150",
    description:
      "A gentle cleanser that hydrates dry skin while removing impurities.",
    ingredients: ["Hyaluronic Acid", "Glycerin", "Aloe Vera"],
    usage: "Apply to wet face, massage gently, and rinse.",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Oil-Free Moisturizer",
    skinType: "Oily Skin",
    category: "Serum",
    price: 340000,
    image: "https://via.placeholder.com/200x150",
    description: "A lightweight, oil-free moisturizer that controls shine.",
    ingredients: ["Salicylic Acid", "Green Tea Extract"],
    usage: "Apply a small amount to face and neck after cleansing.",
    rating: 4.2,
  },
  {
    id: 3,
    name: "Sensitive Skin Toner",
    skinType: "Normal Skin",
    category: "Toner",
    price: 150000,
    image: "https://via.placeholder.com/200x150",
    description: "A gentle toner that soothes and balances sensitive skin.",
    ingredients: ["Chamomile", "Witch Hazel", "Rose Water"],
    usage: "Apply to a cotton pad and gently wipe over face after cleansing.",
    rating: 4.0,
  },
  {
    id: 4,
    name: "Vitamin C Serum",
    skinType: "All",
    category: "Serum",
    price: 300000,
    image: "https://via.placeholder.com/200x150",
    description: "Brightens and protects skin with potent antioxidants.",
    ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid"],
    usage: "Apply a few drops to face and neck in the morning.",
    rating: 4.7,
  },
  {
    id: 5,
    name: "Gentle Makeup Remover",
    skinType: "Sensitive Skin",
    category: "Tẩy trang",
    price: 180000,
    image: "https://via.placeholder.com/200x150",
    description: "Gently removes makeup without irritating sensitive skin.",
    ingredients: ["Micellar Water", "Aloe Vera", "Glycerin"],
    usage: "Saturate a cotton pad and gently wipe over face to remove makeup.",
    rating: 4.3,
  },
  {
    id: 6,
    name: "Acne Treatment Cream",
    skinType: "Oily Skin",
    category: "Kem trị mụn",
    price: 280000,
    image: "https://via.placeholder.com/200x150",
    description: "Targets and treats acne breakouts effectively.",
    ingredients: ["Benzoyl Peroxide", "Tea Tree Oil"],
    usage: "Apply a thin layer to affected areas after cleansing.",
    rating: 3.9,
  },
  {
    id: 7,
    name: "Sun Protection SPF 50",
    skinType: "All",
    category: "Kem chống nắng",
    price: 280000,
    image: "https://via.placeholder.com/200x150",
    description: "Provides broad-spectrum protection from harmful UV rays.",
    ingredients: ["Zinc Oxide", "Titanium Dioxide"],
    usage: "Apply liberally 15 minutes before sun exposure.",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Night Repair Serum",
    skinType: "Dry Skin",
    category: "Serum",
    price: 300000,
    image: "https://via.placeholder.com/200x150",
    description: "Repairs and rejuvenates skin overnight.",
    ingredients: ["Retinol", "Peptides", "Hyaluronic Acid"],
    usage: "Apply a few drops to face and neck at night.",
    rating: 4.8,
  },
];

export default products;
