const products = [
  {
    id: 1,
    name: "Hydrating Facial Cleanser",
    skinType: "Da khô",
    category: "Sữa rửa mặt",
    price: 220000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "A gentle cleanser for dry skin.",
    ingredients: ["Hyaluronic Acid", "Glycerin", "Aloe Vera"],
    usage: "Apply to wet face, massage, and rinse.",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Oil-Free Moisturizer",
    skinType: "Da dầu",
    category: "Serum",
    price: 340000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Controls shine and minimizes pores.",
    ingredients: ["Salicylic Acid", "Green Tea Extract"],
    usage: "Apply to face and neck after cleansing.",
    rating: 4.2,
  },
  {
    id: 3,
    name: "Sensitive Skin Toner",
    skinType: "Da thường",
    category: "Toner",
    price: 150000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Soothes and balances sensitive skin.",
    ingredients: ["Chamomile", "Witch Hazel", "Rose Water"],
    usage: "Apply to cotton pad and wipe over face.",
    rating: 4.0,
  },
  {
    id: 4,
    name: "Vitamin C Serum",
    skinType: "Da hỗn hợp",
    category: "Serum",
    price: 300000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Brightens and protects skin with antioxidants.",
    ingredients: ["Vitamin C", "Vitamin E", "Ferulic Acid"],
    usage: "Apply a few drops in the morning.",
    rating: 4.7,
  },
  {
    id: 5,
    name: "Gentle Makeup Remover",
    skinType: "Da hỗn hợp",
    category: "Tẩy trang",
    price: 180000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Removes makeup without irritation.",
    ingredients: ["Micellar Water", "Aloe Vera", "Glycerin"],
    usage: "Saturate cotton pad and wipe over face.",
    rating: 4.3,
  },
  {
    id: 6,
    name: "Acne Treatment Cream",
    skinType: "Da dầu",
    category: "Kem trị mụn",
    price: 280000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Targets and treats acne breakouts.",
    ingredients: ["Benzoyl Peroxide", "Tea Tree Oil"],
    usage: "Apply a thin layer to affected areas.",
    rating: 3.9,
  },
  {
    id: 7,
    name: "Sun Protection SPF 50",
    skinType: "Da thường",
    category: "Kem chống nắng",
    price: 280000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Provides broad-spectrum protection from UV rays.",
    ingredients: ["Zinc Oxide", "Titanium Dioxide"],
    usage: "Apply 15 minutes before sun exposure.",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Night Repair Serum",
    skinType: "Da khô",
    category: "Serum",
    price: 300000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Repairs and rejuvenates skin overnight.",
    ingredients: ["Retinol", "Peptides", "Hyaluronic Acid"],
    usage: "Apply a few drops at night.",
    rating: 4.8,
  },
  {
    id: 9,
    name: "Clay Mask",
    skinType: "Da dầu",
    category: "Mặt nạ",
    price: 250000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Deep cleanses and purifies oily skin.",
    ingredients: ["Bentonite Clay", "Activated Charcoal"],
    usage: "Apply to face, leave on for 10 minutes, rinse.",
    rating: 4.3,
  },
  {
    id: 10,
    name: "Exfoliating Scrub",
    skinType: "Da hỗn hợp",
    category: "Tẩy tế bào chết",
    price: 200000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Gently removes dead skin cells.",
    ingredients: ["Jojoba Beads", "Salicylic Acid"],
    usage: "Massage onto wet skin, rinse thoroughly.",
    rating: 4.5,
  },
  {
    id: 11,
    name: "Moisturizing Toner",
    skinType: "Da khô",
    category: "Toner",
    price: 180000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Hydrates and soothes dry skin.",
    ingredients: ["Hyaluronic Acid", "Rose Water"],
    usage: "Apply with a cotton pad after cleansing.",
    rating: 4.2,
  },
  {
    id: 12,
    name: "Lightweight Sunscreen",
    skinType: "Da dầu",
    category: "Kem chống nắng",
    price: 320000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Non-greasy sun protection for oily skin.",
    ingredients: ["Zinc Oxide", "Titanium Dioxide"],
    usage: "Apply liberally before sun exposure.",
    rating: 4.7,
  },
  {
    id: 13,
    name: "Oil Cleansing Balm",
    skinType: "Da hỗn hợp",
    category: "Tẩy trang",
    price: 260000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Melts away makeup and impurities.",
    ingredients: ["Olive Oil", "Shea Butter"],
    usage: "Massage onto dry skin, rinse with water.",
    rating: 4.6,
  },
  {
    id: 14,
    name: "Blemish Treatment",
    skinType: "Da dầu",
    category: "Kem trị mụn",
    price: 240000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Reduces redness and inflammation.",
    ingredients: ["Salicylic Acid", "Tea Tree Oil"],
    usage: "Apply directly to blemishes.",
    rating: 4.1,
  },
  {
    id: 15,
    name: "Nourishing Night Cream",
    skinType: "Da khô",
    category: "Kem dưỡng da",
    price: 350000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Nourishes and hydrates dry skin overnight.",
    ingredients: ["Hyaluronic Acid", "Shea Butter", "Ceramides"],
    usage: "Apply to face and neck before bed.",
    rating: 4.9,
  },
  {
    id: 16,
    name: "Balancing Toner",
    skinType: "Da hỗn hợp",
    category: "Toner",
    price: 190000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Balances oil production and hydrates skin.",
    ingredients: ["Witch Hazel", "Aloe Vera", "Rose Water"],
    usage: "Apply with a cotton pad after cleansing.",
    rating: 4.4,
  },
  {
    id: 17,
    name: "Hydrating Serum",
    skinType: "Da khô",
    category: "Serum",
    price: 320000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Provides intense hydration for dry skin.",
    ingredients: ["Hyaluronic Acid", "Vitamin B5"],
    usage: "Apply a few drops to face and neck.",
    rating: 4.7,
  },
  {
    id: 18,
    name: "Daily Facial Cleanser",
    skinType: "Da thường",
    category: "Sữa rửa mặt",
    price: 200000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Gently cleanses and refreshes normal skin.",
    ingredients: ["Aloe Vera", "Chamomile"],
    usage: "Massage onto wet skin, rinse thoroughly.",
    rating: 4.3,
  },
  {
    id: 19,
    name: "Makeup Remover Wipes",
    skinType: "Da hỗn hợp",
    category: "Tẩy trang",
    price: 170000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Convenient for removing makeup on-the-go.",
    ingredients: ["Micellar Water", "Aloe Vera"],
    usage: "Gently wipe face to remove makeup.",
    rating: 4.0,
  },
  {
    id: 20,
    name: "Acne Spot Treatment",
    skinType: "Da dầu",
    category: "Kem trị mụn",
    price: 230000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Quickly reduces acne and blemishes.",
    ingredients: ["Benzoyl Peroxide", "Salicylic Acid"],
    usage: "Apply to affected areas only.",
    rating: 4.4,
  },
    {
    id: 21,
    name: "Hydrating Sunscreen",
    skinType: "Da khô",
    category: "Kem chống nắng",
    price: 310000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Hydrates dry skin while protecting from the sun.",
    ingredients: ["Hyaluronic Acid", "Zinc Oxide"],
    usage: "Apply liberally before sun exposure.",
    rating: 4.8,
  },
  {
    id: 22,
    name: "Nighttime Repair Cream",
    skinType: "Da hỗn hợp",
    category: "Kem dưỡng da",
    price: 330000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Repairs and rejuvenates skin while you sleep.",
    ingredients: ["Retinol", "Peptides", "Ceramides"],
    usage: "Apply to face and neck before bed.",
    rating: 4.6,
  },
  {
    id: 23,
    name: "Pore Minimizing Toner",
    skinType: "Da dầu",
    category: "Toner",
    price: 190000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Tightens pores and controls oil.",
    ingredients: ["Witch Hazel", "Salicylic Acid"],
    usage: "Apply with a cotton pad after cleansing.",
    rating: 4.2,
  },
  {
    id: 24,
    name: "Brightening Serum",
    skinType: "Da thường",
    category: "Serum",
    price: 350000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Brightens and evens skin tone.",
    ingredients: ["Vitamin C", "Niacinamide"],
    usage: "Apply a few drops to face and neck.",
    rating: 4.9,
  },
  {
    id: 25,
    name: "Soothing Cleansing Oil",
    skinType: "Da khô",
    category: "Tẩy trang",
    price: 270000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Gently removes makeup and cleanses dry skin.",
    ingredients: ["Jojoba Oil", "Vitamin E"],
    usage: "Massage onto dry skin, rinse with water.",
    rating: 4.7,
  },
   {
    id: 26,
    name: "Anti-Acne Cleanser",
    skinType: "Da dầu",
    category: "Sữa rửa mặt",
    price: 210000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Helps fight acne and blemishes",
    ingredients: ["Salicylic Acid", "Tea Tree Oil"],
    usage: "Apply to wet face, massage, and rinse.",
    rating: 4.3,
  },
   {
    id: 27,
    name: "Daily Moisturizing Lotion",
    skinType: "Da thường",
    category: "Kem dưỡng da",
    price: 290000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Perfect for everyday use and hydration",
    ingredients: ["Hyaluronic Acid", "Vitamin E"],
    usage: "Apply to face and neck after cleansing",
    rating: 4.5,
  },
   {
    id: 28,
    name: "Calming Makeup Wipes",
    skinType: "Da hỗn hợp",
    category: "Tẩy trang",
    price: 190000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Removes makeup without irritation",
    ingredients: ["Micellar Water", "Aloe Vera", "Green Tea"],
    usage: "Gently wipe face to remove makeup.",
    rating: 4.1,
  },
  {
    id: 29,
    name: "Clear Skin Spot Treatment",
    skinType: "Da dầu",
    category: "Kem trị mụn",
    price: 250000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Effectively treats acne and reduces redness",
    ingredients: ["Benzoyl Peroxide", "Salicylic Acid", "Tea Tree Oil"],
    usage: "Apply to affected areas only.",
    rating: 4.4,
  },
    {
    id: 30,
    name: "Reef Safe Sunscreen SPF 30",
    skinType: "Da thường",
    category: "Kem chống nắng",
    price: 330000,
    image: "https://i.pinimg.com/736x/5c/c3/db/5cc3db62364f9180b8250fc5a56f4fec.jpg",
    description: "Eco-friendly and safe for all skin types",
    ingredients: ["Zinc Oxide", "Titanium Dioxide"],
    usage: "Apply liberally before sun exposure.",
    rating: 4.7,
  },
];

export default products;